import db, { initSchema } from './db.js';

/**
 * Partner analytical / research testing labs across the US.
 * Used for "send peptides for testing" + nearby lab finder.
 */
const LABS = [
  {
    slug: 'pacific-identity-lab-la',
    name: 'Pacific Identity Analytics',
    description: 'HPLC purity and mass-spec identity testing for research peptides.',
    address: '1200 Research Blvd',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90024',
    lat: 34.0689,
    lng: -118.4452,
    phone: '(310) 555-0142',
    email: 'intake@pacificidentity.example',
    website: 'https://example.com/pacific-identity',
    services: 'HPLC purity, LC-MS identity, residual solvent screen',
    turnaround: '5–8 business days',
  },
  {
    slug: 'bay-area-peptide-qc',
    name: 'Bay Area Peptide QC',
    description: 'Third-party identity confirmation for lyophilized research compounds.',
    address: '88 Gateway Park Dr',
    city: 'San Francisco',
    state: 'CA',
    zip: '94107',
    lat: 37.7749,
    lng: -122.4194,
    phone: '(415) 555-0198',
    email: 'labs@bapqc.example',
    website: 'https://example.com/bapqc',
    services: 'HPLC, MS, endotoxin (research samples)',
    turnaround: '4–7 business days',
  },
  {
    slug: 'cascade-analytics-seattle',
    name: 'Cascade Analytics Northwest',
    description: 'Independent lab supporting peptide identity and purity reports.',
    address: '450 Lake Union Way',
    city: 'Seattle',
    state: 'WA',
    zip: '98109',
    lat: 47.6205,
    lng: -122.3493,
    phone: '(206) 555-0177',
    email: 'receive@cascadeanalytics.example',
    website: 'https://example.com/cascade',
    services: 'HPLC, MS, appearance & water content',
    turnaround: '6–10 business days',
  },
  {
    slug: 'desert-peak-lab-phoenix',
    name: 'Desert Peak Analytical',
    description: 'Research compound testing with cold-chain intake.',
    address: '2100 BioPark Rd',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85004',
    lat: 33.4484,
    lng: -112.074,
    phone: '(602) 555-0133',
    email: 'samples@desertpeak.example',
    website: 'https://example.com/desertpeak',
    services: 'HPLC purity, MS identity',
    turnaround: '5–9 business days',
  },
  {
    slug: 'rockies-chem-denver',
    name: 'Rockies Chem Verification',
    description: 'Front-range partner lab for peptide lot confirmation.',
    address: '77 Highlands Science Cir',
    city: 'Denver',
    state: 'CO',
    zip: '80202',
    lat: 39.7392,
    lng: -104.9903,
    phone: '(303) 555-0164',
    email: 'intake@rockieschem.example',
    website: 'https://example.com/rockies',
    services: 'HPLC, MS, Certificate of Analysis packet',
    turnaround: '5–8 business days',
  },
  {
    slug: 'lonestar-spectra-austin',
    name: 'Lone Star Spectra Lab',
    description: 'Texas-based HPLC/MS testing for research peptides.',
    address: '900 Innovation Loop',
    city: 'Austin',
    state: 'TX',
    zip: '78701',
    lat: 30.2672,
    lng: -97.7431,
    phone: '(512) 555-0188',
    email: 'labs@lonestarspectra.example',
    website: 'https://example.com/lonestar',
    services: 'HPLC purity, LC-MS, residual TFA screen',
    turnaround: '4–7 business days',
  },
  {
    slug: 'gulf-coast-identity-houston',
    name: 'Gulf Coast Identity Lab',
    description: 'Accepts research peptide shipments for purity confirmation.',
    address: '3300 Medical Center Blvd',
    city: 'Houston',
    state: 'TX',
    zip: '77030',
    lat: 29.7604,
    lng: -95.3698,
    phone: '(713) 555-0129',
    email: 'receive@gulfcoastid.example',
    website: 'https://example.com/gulfcoast',
    services: 'HPLC, MS, endotoxin research screen',
    turnaround: '5–9 business days',
  },
  {
    slug: 'midwest-purity-chicago',
    name: 'Midwest Purity Partners',
    description: 'Chicago-area third-party testing for lyophilized research compounds.',
    address: '1400 Lake Shore Analytical',
    city: 'Chicago',
    state: 'IL',
    zip: '60611',
    lat: 41.8925,
    lng: -87.622,
    phone: '(312) 555-0155',
    email: 'intake@midwestpurity.example',
    website: 'https://example.com/midwestpurity',
    services: 'HPLC purity, MS identity, moisture',
    turnaround: '5–8 business days',
  },
  {
    slug: 'great-lakes-ms-detroit',
    name: 'Great Lakes MS Center',
    description: 'Mass spectrometry focused research peptide verification.',
    address: '55 Riverfront Lab Way',
    city: 'Detroit',
    state: 'MI',
    zip: '48226',
    lat: 42.3314,
    lng: -83.0458,
    phone: '(313) 555-0140',
    email: 'labs@greatlakesms.example',
    website: 'https://example.com/greatlakesms',
    services: 'LC-MS identity, HPLC purity',
    turnaround: '6–10 business days',
  },
  {
    slug: 'twin-cities-assay',
    name: 'Twin Cities Assay Group',
    description: 'Independent assay lab accepting research peptide samples.',
    address: '200 University Research Park',
    city: 'Minneapolis',
    state: 'MN',
    zip: '55414',
    lat: 44.9778,
    lng: -93.265,
    phone: '(612) 555-0191',
    email: 'samples@tcaassay.example',
    website: 'https://example.com/tcaassay',
    services: 'HPLC, MS, appearance documentation',
    turnaround: '5–8 business days',
  },
  {
    slug: 'gateway-analytics-stl',
    name: 'Gateway Analytics STL',
    description: 'St. Louis partner lab for peptide purity reports.',
    address: '18 Cortex District',
    city: 'St. Louis',
    state: 'MO',
    zip: '63108',
    lat: 38.647,
    lng: -90.254,
    phone: '(314) 555-0162',
    email: 'intake@gatewayanalytics.example',
    website: 'https://example.com/gateway',
    services: 'HPLC purity, MS identity',
    turnaround: '5–9 business days',
  },
  {
    slug: 'atlanta-biospectra',
    name: 'Atlanta BioSpectra',
    description: 'Southeast regional lab for research peptide confirmation.',
    address: '700 Tech Square NE',
    city: 'Atlanta',
    state: 'GA',
    zip: '30308',
    lat: 33.7756,
    lng: -84.3963,
    phone: '(404) 555-0174',
    email: 'labs@atlantabiospectra.example',
    website: 'https://example.com/atlbiospectra',
    services: 'HPLC, LC-MS, Certificate of Analysis draft',
    turnaround: '4–7 business days',
  },
  {
    slug: 'sunshine-state-qc-miami',
    name: 'Sunshine State QC',
    description: 'Miami intake for peptide identity and purity testing.',
    address: '350 Brickell Research Row',
    city: 'Miami',
    state: 'FL',
    zip: '33131',
    lat: 25.7617,
    lng: -80.1918,
    phone: '(305) 555-0183',
    email: 'receive@sunshineqc.example',
    website: 'https://example.com/sunshineqc',
    services: 'HPLC purity, MS identity, cold-chain intake',
    turnaround: '5–8 business days',
  },
  {
    slug: 'orlando-compound-lab',
    name: 'Orlando Compound Verification',
    description: 'Central Florida analytical support for research peptides.',
    address: '90 Lake Nona Lab Park',
    city: 'Orlando',
    state: 'FL',
    zip: '32827',
    lat: 28.4312,
    lng: -81.308,
    phone: '(407) 555-0118',
    email: 'intake@orlandocompound.example',
    website: 'https://example.com/orlandocv',
    services: 'HPLC, MS',
    turnaround: '6–9 business days',
  },
  {
    slug: 'capitol-purity-dc',
    name: 'Capitol Purity Lab',
    description: 'Mid-Atlantic partner for independent peptide testing.',
    address: '1100 New York Ave NW',
    city: 'Washington',
    state: 'DC',
    zip: '20005',
    lat: 38.9007,
    lng: -77.0267,
    phone: '(202) 555-0199',
    email: 'labs@capitolpurity.example',
    website: 'https://example.com/capitolpurity',
    services: 'HPLC purity, MS identity',
    turnaround: '5–8 business days',
  },
  {
    slug: 'mid-atlantic-ms-philly',
    name: 'Mid-Atlantic MS Lab',
    description: 'Philadelphia-area mass-spec identity confirmation.',
    address: '401 University City Science Ctr',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19104',
    lat: 39.9526,
    lng: -75.1652,
    phone: '(215) 555-0147',
    email: 'samples@mams.example',
    website: 'https://example.com/mams',
    services: 'LC-MS, HPLC purity',
    turnaround: '5–8 business days',
  },
  {
    slug: 'empire-state-assay-nyc',
    name: 'Empire State Assay',
    description: 'NYC metro lab accepting research peptide shipments.',
    address: '222 Alexandria Center',
    city: 'New York',
    state: 'NY',
    zip: '10016',
    lat: 40.7421,
    lng: -73.974,
    phone: '(212) 555-0136',
    email: 'intake@empireassay.example',
    website: 'https://example.com/empireassay',
    services: 'HPLC, MS, residual solvent screen',
    turnaround: '4–7 business days',
  },
  {
    slug: 'hudson-valley-chem-boston',
    name: 'Harbor Chem Verification',
    description: 'Boston research corridor peptide testing partner.',
    address: '500 Kendall Square',
    city: 'Cambridge',
    state: 'MA',
    zip: '02142',
    lat: 42.3626,
    lng: -71.0843,
    phone: '(617) 555-0159',
    email: 'labs@harborchem.example',
    website: 'https://example.com/harborchem',
    services: 'HPLC purity, MS identity, endotoxin research screen',
    turnaround: '4–7 business days',
  },
  {
    slug: 'carolina-research-assay',
    name: 'Carolina Research Assay',
    description: 'Raleigh-Durham partner for peptide lot confirmation.',
    address: '100 RTP Lab Drive',
    city: 'Durham',
    state: 'NC',
    zip: '27709',
    lat: 35.8992,
    lng: -78.8636,
    phone: '(919) 555-0122',
    email: 'receive@carolinaassay.example',
    website: 'https://example.com/carolinaassay',
    services: 'HPLC, MS, CoA packet',
    turnaround: '5–8 business days',
  },
  {
    slug: 'ohio-valley-purity',
    name: 'Ohio Valley Purity Lab',
    description: 'Columbus-area independent testing for research compounds.',
    address: '70 Innovation Way',
    city: 'Columbus',
    state: 'OH',
    zip: '43215',
    lat: 39.9612,
    lng: -82.9988,
    phone: '(614) 555-0171',
    email: 'intake@ohiovalley.example',
    website: 'https://example.com/ohiovalley',
    services: 'HPLC purity, MS identity',
    turnaround: '5–9 business days',
  },
  {
    slug: 'music-city-ms-nashville',
    name: 'Music City MS Lab',
    description: 'Nashville partner lab for peptide identity reports.',
    address: '45 Music Row Research Annex',
    city: 'Nashville',
    state: 'TN',
    zip: '37203',
    lat: 36.1527,
    lng: -86.789,
    phone: '(615) 555-0168',
    email: 'labs@musiccityms.example',
    website: 'https://example.com/musiccityms',
    services: 'LC-MS, HPLC',
    turnaround: '6–10 business days',
  },
  {
    slug: 'desert-research-vegas',
    name: 'Desert Research Analytics',
    description: 'Las Vegas intake for research peptide purity testing.',
    address: '3000 Research Park Dr',
    city: 'Las Vegas',
    state: 'NV',
    zip: '89119',
    lat: 36.084,
    lng: -115.1537,
    phone: '(702) 555-0144',
    email: 'samples@desertresearch.example',
    website: 'https://example.com/desertresearch',
    services: 'HPLC purity, MS identity',
    turnaround: '5–8 business days',
  },
  {
    slug: 'salt-flats-qc-slc',
    name: 'Salt Flats QC',
    description: 'Salt Lake City analytical support for research peptides.',
    address: '15 Research Park Blvd',
    city: 'Salt Lake City',
    state: 'UT',
    zip: '84108',
    lat: 40.7608,
    lng: -111.891,
    phone: '(801) 555-0131',
    email: 'intake@saltflatsqc.example',
    website: 'https://example.com/saltflatsqc',
    services: 'HPLC, MS, moisture',
    turnaround: '5–8 business days',
  },
  {
    slug: 'pdx-cascade-verify',
    name: 'PDX Cascade Verify',
    description: 'Portland partner for third-party peptide confirmation.',
    address: '2200 South Waterfront',
    city: 'Portland',
    state: 'OR',
    zip: '97201',
    lat: 45.495,
    lng: -122.671,
    phone: '(503) 555-0152',
    email: 'labs@pdxcascade.example',
    website: 'https://example.com/pdxcascade',
    services: 'HPLC purity, MS identity',
    turnaround: '5–9 business days',
  },
];

export function ensureTestingLabs() {
  initSchema();
  const count = db.prepare('SELECT COUNT(*) AS c FROM testing_labs').get().c;
  if (count > 0) {
    return { skipped: true, count };
  }

  const insert = db.prepare(`
    INSERT INTO testing_labs (
      slug, name, description, address, city, state, zip, country,
      lat, lng, phone, email, website, services, turnaround,
      accepts_shipments, is_partner
    ) VALUES (
      @slug, @name, @description, @address, @city, @state, @zip, 'US',
      @lat, @lng, @phone, @email, @website, @services, @turnaround,
      1, 1
    )
  `);

  const run = db.transaction(() => {
    for (const lab of LABS) insert.run(lab);
  });
  run();

  return {
    skipped: false,
    count: db.prepare('SELECT COUNT(*) AS c FROM testing_labs').get().c,
  };
}
